# 这是一个尸潮的完整配置文件
# 所有支持的功能都在这儿了！


# 是否启用这个尸潮
# 若为false，则这个配置文件不会被加载！
enable: false

# 尸潮持续时间
# 设置为-1关闭它(即不会自动停止)
duration: 1200

# 该尸潮开启时广播给玩家的消息
start_message: "§b[§ctideZombie§b]§r:尸潮已经开始..."

# 该尸潮结束时广播给玩家的消息
end_message: "§b[§ctideZombie§b]§r:尸潮已经停止..."

############################################################
##                      刷怪坐标生成设置                      ##
############################################################
# 这个尸潮如何生成刷怪坐标？

# 刷怪坐标生成方式
# 这是为将来的功能所准备的,不要修改它！
generate_loc_type: "around_player"

# 这个尸潮在哪些世界刷怪
enable_worlds:
- world

# 最远刷怪半径(距离玩家)
max_radius: 64

# 最近刷怪半径(距离玩家)
min_radius: 6

# 刷怪高度半径(距离玩家)
max_Y_radius: 5

# 最高刷怪亮度
# 调低这个值来显著减少刷怪量
max_light: 999

# 多少ticks刷一次怪(每玩家刷一只)
spawn_ticks: 100

# 最多尝试寻找多少次刷怪位置
# 若玩家位于实心区域，或虚空区域，则可能需要多次尝试才能找到合适的刷怪位置
max_try_times: 15

# 是否限制世界最大刷怪上限
limit_mobs: true

# 如果限制了世界最大刷怪上限
# 每个玩家的刷怪上限
max_mob_per_player: 50

# 不能刷怪的方块
# 怪物将不会在下列方块上生成
disable_blocks:
- AIR
- STATIONARY_WATER #静态水方块


############################################################
##                         黑白名单设置                      ##
############################################################
# 管理员福音

# ID黑白名单设置
id_list_setting:
  # 值为1时,ID白名单(white_list_permissions)生效,
  # 值为2时,ID黑名单(black_list_permissions)生效，
  # 值位0时(或该配置项不存在时),ID黑白名单全部失效
  enable: 0

  # 白名单_玩家ID
  # 不会以这些玩家为中心刷怪
  white_list_player_id:
  - smyhw
  - testplayer1

  # 黑名单_玩家ID
  # 只会以这些玩家为中心刷怪
  black_list_player_id:
  - smyhw
  - testplayer1

# 权限黑白名单设置
permissions_list_setting:
  # 值为1时,权限白名单(white_list_permissions)生效,
  # 值为2时,权限黑名单(black_list_permissions)生效，
  # 值位0时(或该配置项不存在时),权限黑白名单全部失效
  enable: 0

  # 白名单_权限
  # 仅在permissions_list_switch为1时生效
  # 不会以拥有以下权限的玩家为中心刷怪
  white_list_permissions:
  - test.ps

  # 黑名单_权限
  # 仅在permissions_list_switch为2时生效
  # 仅以拥有下列权限的玩家为中心刷怪
  black_list_permissions:
  - test.sps

# 刷怪区域
# 若存在此配置项，则：
# 只会以选中区域内的玩家为_中心_刷怪
# (贴士:实际可能刷怪的范围还得计算你的刷怪半径哦)
# 这是一个列表，便于指定多个区域
# 格式[x范围]&[y范围]&[z范围]
# 注意:不能有空格
# 例如: "100~200&64~100&200~300"
#     代表x轴100到200之间,y轴64~100之间,z轴200~300之间,在这个空间内的玩家的周围会刷怪
#
# 删掉该配置项目可以禁用这个特性
area_list:
- "100~200&64~100&200~300"

############################################################
##                         怪物生成设置                      ##
############################################################
# 这个尸潮如何生成怪物（生成哪些怪物）?

# 这个值为"cmd"时,使用指令(即下文spawn_cmds项目)生成怪物
#    这个生成方式可以使用例如mm的刷怪指令
# 这个值为"def"时,直接生成(使用下文enable_mob项目规定的类型)
#    这个刷怪方式将被其他插件认作自然刷怪,可以兼容例如精英怪之类的自然刷怪增强插件
summon_mob_type: "def"


# 如果上面"summon_mob_type"为def的话，使用下面的列表生成怪物
# 刷怪的列表
# 每种怪物将随机生成
enable_mob:
- ZOMBIE

# 如果上面"summon_mob_type"为cmd的话，使用这个指令列表生成怪物
# 将随机挑选指令执行
# %x%/%y%/%z%三个变量将替换为刷怪的坐标
# %world%将被替换为世界名称
# "player:"开头将给予当前世界的一个随机玩家临时的op权限并执行该刷怪指令，适用于不提供world选项，直接使用指令执行人所在的世界的刷怪命令
spawn_cmds:
- "mm mobs spawn Messenger 1 %world%,%x%,%y%,%z%"
- "player:summon Zombie %x% %y% %z%"


############################################################
##                          触发器设置                      ##
############################################################
# 这里定义了这个尸潮该何时启动

trigger:
  # 这是触发器的类别，不同的类别有不同的参数可以配置
  # 类别"OnNightStartTrigger"的作用是在夜晚到来时开始尸潮
  # 这相当与在14000ticks时开始目标尸潮
  # 一般情况下,mc的夜晚有10000tick
  # 所以,你可以在目标尸潮中配置"duration:10000"来创建一个只在夜晚开启的尸潮
  type: "OnNightStartTrigger"

  # 以哪个世界的时间为准
  on_night_world: world

  # 间隔，每次尸潮间间隔多少天(默认0天,即每天晚上都有尸潮)
  interval: 0