#在哪些世界开启
enable_worlds:
- world
#最远刷怪半径(距离玩家)
max_radius: 64
#最近刷怪半径(距离玩家)
min_radius: 9
#刷怪高度半径(距离玩家)
max_Y_radius: 5
#多少ticks刷一次怪(每玩家刷一只)
spawn_ticks: 200
#最高尝试次数
#最多尝试寻找多少次刷怪位置
#当你的玩家把他刷怪半径中的所有方块全部填实的时候,
#降低它以减少疯狂的玩家造成的卡顿
max_try_times: 15
#每个玩家的最大刷怪半径中最多存在多少只怪
max_mob_per_player: 15
#刷怪的列表
enable_mob:
- ZOMBIE